### ISSUE TITLE
How to organise the NB directory?

### ISSUE THREAD

**Issue by jjgomezcadenas** [nextic/Notebooks#12]
In previous discussion we reached the fuzzy consensus that the NB central repository would have only  accept mature "deliverable" NBs, while developers would keep their own "draft" NBs in their forks.

I am not sure this is a good scheme.

The problem is this. Suppose that developer Amy is working in a krypton analysis. She goes ahead and produces 20 Nbs, that live on her fork. Now, eventually she wants to deliver a single kryptonite.ipynb NB. How does she do it?

She needs to create a branch and then make a PR. But the branch has to start somewhere, and it must not contain all her 20 drafts. Not a pretty situation. As time goes by, her fork is diverging exponentially from the central repository, and each time she needs to commit something there, creating the corresponding branch becomes a pain. 

I think there is a better solution. The Notebook repository should have two main folders,

develop.   deliver

inside develop folders correspond to developers

Amy Sheldom Penny ... etc

Each developer commits her work to her own area and in such a way she is always in sync (or can get easily in sync) with the main repository. In addition, she can now commit to the folder deliver, which is organised like IC

cities core analysis... etc

Then, when she wants to prepare a branch to upload, say, kryptonite.ipynb, she can simply copy her kryptonite_version_20.ipynb from /develop/Amy/Analysis/Krypton to /deliver/analyisis/krypton/kyptonite.ipynb 

the PR will include not only kriptonyte.ipynb, but also the whole snapshot of her repository, but this is fine, since there is no conflict with others now.

While Amy works in Krypton, Sheldom works in Na-22 and Penny works in Co-56. Each successive PR adds their work to their local area in the central repository and the delivery product to the deliver area. Tipically they will make only a PR when they have a deliver product, but at time particular moment, they will upload also the work that led to that delivery product (which is then collected and traced at the level of central repository).

To keep the repository lean, we can choose that only stripped .ipynb and .py files are admitted in the develop area of the central repository (e.g, no html). This is easy to implement for Amy et al, since all what she needs to do is to delete the .html files in the PR branch. In the deliver area we want, of course, the html also. 

I think this scheme gives us a viable solution for the Notebooks. My impression is that there will be a lot of development with Notebooks, and this scheme allows us to keep some control over it.

**Comment by jacg** [comment]
@jjgomezcadenas Sorry, don't have time to read/think in detail, but at first blush it looks like here

> The Notebook repository should have two main folders,
> 
> develop. deliver

You don't want separate directories in the main repo, but separate branches in the developer's repo.

Please don't commit anything before we've had a chance to talk about it. (We could talk in person in CERN Resto 2 between 12:10 and 12:50 today, if it's urgent.)

**Comment by jjgomezcadenas** [comment]
OK, let’s talk at 12:10 at Resto 2 (it’s urgent)

**Comment by jacg** [comment]
Better still, come to the Training Centre at 12, then we can talk on the way.

**Comment by jmbenlloch** [comment]
As @jacg suggested, there is indeed a way to copy files from one branch to another (and a magit command for doing that). Therefore, the idea could be:

Each developer has two branches in their forks: development and delivery. Usually she would work in 'development' branch, with as many notebooks as she needs. All this will be only in her fork. When a notebook is mature enough to go to the central repository, it should be copied from development branch to delivery branch. This can be done with the git command (being in delivery branch):

`git checkout development myfile.ipynb`

In magit you can use the command `magit-file-checkout`, I don't know if there is a default shortcut for it.

Then she can make a new pull request from delivery branch containing only the final products.

**Comment by jjgomezcadenas** [comment]
OK. To complete the picture. Although Jupiter can generate automatically .html and .py files is better not to do it by default (otherwise you have a new .html each time you change output and back to the same problem we want to cure). Indeed, the developer branch does not need .html at all, since our generic developer (Amy) has anyway the .ipynb on her working area. Once her final product (kryptonite.ipynb) is checked out in the delivery branch, and before she makes a pull request, she generates manually .py and .html files and PR the (stripped) .ipynb, .html and .py

Unless any one complains, I think this completes the picture. If I don’t hear complains from the Jedi I will close the issue tomorrow.
J

**Comment by jjgomezcadenas** [comment]
In fact, neither deliver, nor develop are needed at all. The use can choose any workflow, moving around between branches as she wishes. Then, when she is ready to propose a pull request she can create a deliver branch, cherry pick the files she needs, commit, PR and delete the branch.

**Comment by jacg** [comment]
Yes, the developer is free to use whatever private branches he wants.

I'll need a few minutes to think about the html generation. We don't want anything generated (be it HTML or notebook output cells) to be version controlled, but we *do* want these to be available out of the box: you shouldn't have to repeat the calculations yourself to see the results. Without thought, it's not clear to me how to satisfy both of these requirements. But I suspect that we are not the first to be confronted with this.

**Comment by jjgomezcadenas** [comment]
I close this issue, as we won't have a Notebook directory. For the time being the solutions being considered as:

1) Notebooks (stripped) are committed to git
2) Notebooks (html) are uploaded to a dedicated gallery... or...
3) Notebooks (.ipynb) are uploaded to ANACONDA cloud (separate issue)

The discussion of the various possibilities goes to a separate issue.
